services:
  # PHP Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory (php-lms)
    container_name: php_lms_app
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Apache)
    volumes:
      - ./src:/var/www/html # Mount local src directory to container's web root
    depends_on:
      - db # Ensure db starts before the app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: php_lms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this in a real project!
      MYSQL_DATABASE: lms_db
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-prootpassword"]
        timeout: 20s
        retries: 10

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_lms_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80" # Map host port 8081 to container port 80
    environment:
      PMA_HOST: db # Connect to the 'db' service hostname
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword # Use the same root password as the db service
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy

volumes:
  db_data: # Define the named volume for database persistence
